//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZPW.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegExpResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegExpResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZPW.Util.Properties.RegExpResource", typeof(RegExpResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ^([0-9a-zA-Z]+[-._+&amp;])*[0-9a-zA-Z]+@([0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}$ 的本地化字符串。
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^0\d{2,3}(\-)?\d{7,8}$ 的本地化字符串。
        /// </summary>
        internal static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^\+?[1-9][0-9]*$ 的本地化字符串。
        /// </summary>
        internal static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(?&lt;First&gt;2[0-4]\d|25[0-5]|[01]?\d\d?)\.(?&lt;Second&gt;2[0-4]\d|25[0-5]|[01]?\d\d?)\.(?&lt;Third&gt;2[0-4]\d|25[0-5]|[01]?\d\d?)\.(?&lt;Fourth&gt;2[0-4]\d|25[0-5]|[01]?\d\d?)$ 的本地化字符串。
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(1(([35][0-9])|(47)|(70)|[8][012356789]))\d{8}$ 的本地化字符串。
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[0-9]+(.[0-9]{2})?$ 的本地化字符串。
        /// </summary>
        internal static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[A-Za-z]+$ 的本地化字符串。
        /// </summary>
        internal static string OnlyAlpha {
            get {
                return ResourceManager.GetString("OnlyAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[A-Za-z0-9]+$ 的本地化字符串。
        /// </summary>
        internal static string OnlyAlphaAndNumber {
            get {
                return ResourceManager.GetString("OnlyAlphaAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[a-z]+$ 的本地化字符串。
        /// </summary>
        internal static string OnlyAlphaLower {
            get {
                return ResourceManager.GetString("OnlyAlphaLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[A-Z]+$ 的本地化字符串。
        /// </summary>
        internal static string OnlyAlphaUpper {
            get {
                return ResourceManager.GetString("OnlyAlphaUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^[\u4e00-\u9fa5]{0,}$ 的本地化字符串。
        /// </summary>
        internal static string OnlyChinese {
            get {
                return ResourceManager.GetString("OnlyChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^([1-9]\d*)$|^0$ 的本地化字符串。
        /// </summary>
        internal static string OnlyNumber {
            get {
                return ResourceManager.GetString("OnlyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ^(?&lt;Protocol&gt;\w+):\/\/(?&lt;Domain&gt;[\w.]+\/?)\S*$ 的本地化字符串。
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
